---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    
- name: Install Python 3
  ansible.builtin.apt:
    name: python3
    state: present

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install boto3 using pip3
  become: true
  ansible.builtin.pip:
    name: boto3
    state: present

- name: Install AWS CLI using pip
  become: true
  ansible.builtin.pip:
    name: awscli
    state: latest
    executable: pip3

- name: Install Java JDK 17
  ansible.builtin.apt:
    name: openjdk-17-jdk
    state: present